name: Build Tauri App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            imagemagick \
            icnsutils

      - name: Install system dependencies (macOS only)
        if: matrix.os == 'macos-latest'
        run: brew install imagemagick

      - name: Install system dependencies (Windows only)
        if: matrix.os == 'windows-latest'
        run: choco install imagemagick -y

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Generate App Icons
        run: |
          mkdir -p src-tauri/icons

          # Ensure base icon is valid PNG32, resize to 1024x1024
          magick src-tauri/icons/icon.png -resize 1024x1024 -define png:format=png32 src-tauri/icons/icon.png

          # Linux PNGs in all common sizes
          for size in 16 32 48 64 128 256 512 1024; do
            magick src-tauri/icons/icon.png -resize ${size}x${size} -define png:format=png32 src-tauri/icons/icon-${size}.png
          done

          # Windows ICO
          magick src-tauri/icons/icon-16.png src-tauri/icons/icon-32.png src-tauri/icons/icon-48.png src-tauri/icons/icon-64.png src-tauri/icons/icon-128.png src-tauri/icons/icon-256.png src-tauri/icons/icon.ico

          # macOS ICNS (iconutil is built-in on macOS runners)
          mkdir -p src-tauri/icons/macos.iconset
          for size in 16 32 128 256 512 1024; do
            magick src-tauri/icons/icon.png -resize ${size}x${size} src-tauri/icons/macos.iconset/icon_${size}x${size}.png
            magick src-tauri/icons/icon.png -resize $((size*2))x$((size*2)) src-tauri/icons/macos.iconset/icon_${size}x${size}@2x.png
          done
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            iconutil -c icns src-tauri/icons/macos.iconset -o src-tauri/icons/icon.icns
          fi

      - name: Build Tauri App
        run: cargo tauri build
        working-directory: src-tauri

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lonkorush-client-${{ matrix.os }}
          path: src-tauri/target/release/bundle/
