name: build-tauri

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""
          - platform: macos-latest
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # Linux dependencies
      - name: Install dependencies (Linux only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            build-essential \
            curl \
            wget \
            file \
            pkg-config

      # Node (for frontend, adjust if using npm/pnpm instead of yarn)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      # Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # Install frontend deps (falls du src hast)
      - name: Install frontend deps
        run: yarn install

      # Build mit Tauri Action
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}

      # Upload artifacts (statt Release)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lonkorush-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/
