name: Build Tauri App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            libappindicator3-dev \
            imagemagick

      - name: Install system dependencies (macOS only)
        if: matrix.os == 'macos-latest'
        run: brew install imagemagick

      - name: Install system dependencies (Windows only)
        if: matrix.os == 'windows-latest'
        run: choco install imagemagick -y

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Ensure icon is valid PNG32
        run: |
          magick src-tauri/icons/icon.png -define png:format=png32 src-tauri/icons/icon.png

      - name: Build Tauri App
        run: cargo tauri build
        working-directory: src-tauri

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lonkorush-client-${{ matrix.os }}
          path: src-tauri/target/release/bundle/
