name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            imagemagick \
            icnsutils

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install imagemagick icnsutils

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install imagemagick -y --force
          refreshenv

      - name: Fix icons (convert PNG to required formats)
        shell: bash
        run: |
          # Stelle sicher: RGBA PNG
          if command -v magick >/dev/null 2>&1; then
            magick src-tauri/icons/icon.png -define png:format=png32 src-tauri/icons/icon.png
          elif command -v convert >/dev/null 2>&1; then
            convert src-tauri/icons/icon.png -define png:format=png32 src-tauri/icons/icon.png
          fi

          # macOS: .icns bauen
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mkdir -p src-tauri/icons/mac.iconset
            for size in 16 32 128 256 512 1024; do
              magick src-tauri/icons/icon.png -resize ${size}x${size} src-tauri/icons/mac.iconset/icon_${size}x${size}.png
            done
            iconutil -c icns src-tauri/icons/mac.iconset -o src-tauri/icons/icon.icns
          fi

          # Windows: .ico bauen
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            magick src-tauri/icons/icon.png -define icon:auto-resize=256,128,64,48,32,16 src-tauri/icons/icon.ico
          fi

      - name: Install frontend (if needed)
        run: |
          cd src
          if [ -f package.json ]; then
            npm install
            npm run build
          fi
        shell: bash

      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: src-tauri/target/release/bundle/**
